### ISSUE TITLE
prefix_mismatch not considering partial_len on longer partial

### ISSUE THREAD

**Issue by lmcmgig** [armon/libart#24]
The function prefix_mismatch on partial longer than MAX_PREFIX_LEN is incorrect.  If the key search is the lowest key of the next node, a match occur but shouldn't.  So a lot more of results are selected.

In art_iter_prefix, we need to cap the prefix_len found to the partial_len of the current node.  Only one line is impacted:
prefix_len = prefix_mismatch(n, key, key_len, depth);
if(prefix_len > n->partial_len) prefix_len = n->partial_len;

**Comment by armon** [comment]
Fixed in bbbf588. Thanks!
