### ISSUE TITLE
Serializing the tree

### ISSUE THREAD

**Issue by rapoth** [armon/libart#25]
Hi,

This library looks very interesting. Since I do not want to reconstruct the tree everytime I load my program, I was wondering if there is a way I can go about serializing the tree once I build it. Is there a way to do this efficiently?

Thanks!

**Comment by armon** [comment]
@rapoth There is not an integrated method in the library. You would need to walk the tree and serialize it to a format of your choice. Radix tree's are more optimized for in-memory layout than on disk, as opposed to a B-Tree.
