### ISSUE TITLE
Node Header: MAX_PREFIX_LEN & uint8_t num_children

### ISSUE THREAD

**Issue by DeusProx** [armon/libart#36]
Hello!

ATM I'm trying to get into the same paper you implemented here and noticed a problem:

1. You defined the _node header_ with a contant size of 16 Byte like the paper.
2. The paper proposed to store a _compressed path_ of 8 Bytes whilst your implementation defines it through _MAX_PREFIX_LEN_ as 10 Bytes. 
3. Due to the necessity to store a _compressed path_ of 10 Bytes & it's length (4 Bytes), you only have 2 Bytes left to store the _node type_ & the amount of non null children (_num_children_).

Problem:
I think _num_children_ should be an uint16_t since at most we can store 256 children. Thus _num_children_ should cover the integer range 0..256 (257 numbers) which don't fit into an uint8_t.

**Comment by Lecrapouille** [comment]
This is related with https://github.com/armon/libart/issues/34

**Comment by DeusProx** [comment]
House keeping: Related issue seems to be closed
